---
- name: Deploy the nodejs app from a git repository
  git:
    repo: "{{ nodejsapp_repository_url }}"
    dest: "{{ nodejsapp_repository_dest }}"

- name: Setup app service
  block:
    - name: Create the application systemd service
      template:
        src: "{{ nodejsapp_service_file_path }}"
        dest: "/etc/systemd/system/{{ nodejsapp_name }}.service"
      register: nodejsapp_service_file_upload

    - name: Systemd Daemon reload
      shell: systemctl daemon-reload
      when: nodejsapp_service_file_upload.changed

    - name: Set app systemd service
      systemd:
        name: "{{ nodejsapp_name }}"
        state: started
        enabled: yes