---
- name: "Deploy {{ nodejsapp_name }} nodejs app from a git repository"
  git:
    repo: "{{ nodejsapp_repository_url }}"
    dest: "{{ nodejsapp_repository_dest }}"
    force: true
  register: deploy_app
