---
- name: Clone locally before sync on host
  local_action: ansible.builtin.git repo={{ nodejsapp_repository_url }} dest={{ nodejsapp_src_path }} version={{ nodejsapp_version }} force=true
  become: false

- name: Deploy the nodejs app from a local repository
  synchronize:
    src: "{{ nodejsapp_src_path }}/"
    dest: "{{ nodejsapp_repository_dest }}"
    checksum: yes
    owner: no
    # rsync_opts:
    #   - "--exclude=.git"
  notify: Restart nodejsapp service
  register: deploy_app
