---
- name: Add NodeSource package key
  apt_key:
    state: present
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejsapp_nodejs_version_main }}.x bullseye main

- name: NodeJS installed
  apt:
    name: nodejs{% if nodejsapp_nodejs_version | length > 0 %}={{ nodejsapp_nodejs_version }}{% endif %}
    state: present
    allow_downgrade: true
    update_cache: true
