---
- name: Install dependencies
  apt:
    name:
      - gnupg2
      - git
      - rsync
    state: present
    update_cache: true

- name: Upgrade OS
  apt:
    upgrade: dist

- name: Add NodeSource package key
  apt_key:
    state: present
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add NodeSource repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejsapp_node_main_version }}.x bullseye main

- name: NodeJS installed
  apt:
    name: nodejs={{ nodejsapp_node_main_version }}.{{ nodejsapp_node_minor_version }}-deb-1nodesource1
    state: present
    allow_downgrade: true
    update_cache: true