---
- name: Check npm packages outdated
  shell: npm outdated
  args:
    chdir: "{{ nodejsapp_repository_dest }}"
  changed_when: false
  failed_when: false
  register: npm_packages_need_update

- name: Update app node dependencies
  npm:
    path: "{{ nodejsapp_packages_file_directory }}"
    ci: yes
  when: npm_packages_need_update.rc != 0
