---
- name: Check node_modules directory presence
  stat:
    path: "{{ nodejsapp_packages_file_directory }}/node_modules"
  register: npm_node_modules_directory

- name: Check packages-lock file presence
  stat:
    path: "{{ nodejsapp_packages_file_directory }}/package-lock.json"
  register: npm_package_lock_file

- name: Check npm packages outdated
  shell: npm outdated
  args:
    chdir: "{{ nodejsapp_packages_file_directory }}"
  changed_when: false
  failed_when: false
  register: npm_packages_need_update

- name: Setup node dependencies
  npm:
    path: "{{ nodejsapp_packages_file_directory }}"
    ci: "{{ nodejsapp_packages_locked_ci and npm_package_lock_file.stat.exists }}"