---
- name: Setup app service
  block:
    - name: Create the application systemd service
      template:
        src: "{{ nodejsapp_service_file_path }}"
        dest: "/etc/systemd/system/{{ nodejsapp_name }}.service"
      notify: Restart nodejsapp service
