---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: from-public-git
    box: debian/bullseye64
  - name: from-local-clone
    box: debian/bullseye64
provisioner:
  name: ansible
verifier:
  name: testinfra
